db.options:
  driver: pdo_mysql
  host: localhost
  dbname: silex_test
  user: root
  password: root
  charset: utf8

entity:
  namespace: "Xearts\\SilexBase\\Entity"
  path: "/Entity"

console:
  name: "MyApplication"
  version: 1.0.0
