db.options:
  driver: pdo_mysql
  host: localhost
  dbname: silex_test
  user: root
  password: root
  charset: utf8

mail:
    transport: mail
    charset_iso_2022_jp: true

entity:
  namespace: "Xearts\\SilexBase\\Entity"
  path: "/Entity"

console:
  name: "MyApplication"
  version: 1.0.0
